/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Configure external domains for optimized remote images
  // We add allowed domains for images generated by OpenAI's DALL·E service.
  // Without this configuration, Next.js will block remote images from these domains,
  // resulting in broken placeholders on the results page.
  images: {
    domains: [
      'oaidalleapiprodscus.blob.core.windows.net', // default US region for DALL·E images
      'oaidalleapiprod.azureedge.net'             // CDN edge for DALL·E images
    ]
  },
  i18n: {
    locales: ['de', 'en'],
    defaultLocale: 'de'
  }
};

module.exports = nextConfig;